### ISSUE TITLE
Can't delete qdiscs, functionality not yet implemented?

### ISSUE THREAD

**Issue by reprah** [florianl/go-tc#11]
go-tc version: master (69b0c913257724fbbbf4717192143a434c14e88e)
go version: 1.13
OS: Ubuntu 18.04

I’m creating and deleting qdiscs for an interface using these `tc` commands:

```
tc qdisc add dev eth0 root tbf rate 2mbit burst 32kbit latency 400ms
tc qdisc del dev eth0 root
```

I’m trying to achieve the same thing using go-tc. After creating the qdisc using the `tc qdisc add` command above, and selecting it with Qdisc.Get() in this sample program, I’m unable to delete the qdisc:

```
package main

import (
	"fmt"
	"github.com/florianl/go-tc"
	"net"
	"os"
)

func main() {
	rtnl, err := tc.Open(&tc.Config{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not open rtnetlink socket: %v\n", err)
		return
	}
	defer func() {
		if err := rtnl.Close(); err != nil {
			fmt.Fprintf(os.Stderr, "could not close rtnetlink socket: %v\n", err)
		}
	}()

	qdiscs, err := rtnl.Qdisc().Get()

	var targetQdiscs []tc.Object

	if err != nil {
		fmt.Fprintf(os.Stderr, "could not get qdiscs: %v\n", err)
		return
	}
	for _, qdisc := range qdiscs {
		iface, err := net.InterfaceByIndex(int(qdisc.Ifindex))
		if err != nil {
			fmt.Fprintf(os.Stderr, "could not get interface from id %d: %v", qdisc.Ifindex, err)
			return
		}
		if iface.Name == "eth0" && qdisc.Attribute.Kind == "tbf" {
			fmt.Printf("%20s\t%+v\n", iface.Name, qdisc)
			targetQdiscs = append(targetQdiscs, qdisc)
		}
	}

	for _, qdisc := range targetQdiscs {
		if err := rtnl.Qdisc().Delete(&qdisc); err != nil {
			fmt.Fprintf(os.Stderr, "could not delete qdisc: %v\n", err)
			return
		}
	}
}
```
Program output:

```
root@ip-172-22-0-241:~/go/src/tc-test# go build -o tc-test
root@ip-172-22-0-241:~/go/src/tc-test# ./tc-test
                eth0    {Msg:{Family:0 Ifindex:2 Handle:2147549184 Parent:4294967295 Info:2} Attribute:{Kind:tbf EgressBlock:0 IngressBlock:0 HwOffload:0 Chain:0 Stats:0xc00001a2d0 XStats:<nil> Stats2:0xc00001c360 Stab:<nil> Basic:<nil> BPF:<nil> U32:<nil> Rsvp:<nil> Route4:<nil> Fw:<nil> Flow:<nil> Matchall:<nil> Cake:<nil> FqCodel:<nil> Codel:<nil> Fq:<nil> Pie:<nil> Hhf:<nil> Tbf:0xc000086190 Sfb:<nil> Red:<nil> MqPrio:<nil> Pfifo:<nil> Bfifo:<nil> Choke:<nil> Netem:<nil> Htb:<nil> Hfsc:<nil> HfscQOpt:<nil> Dsmark:<nil> Drr:<nil> Cbq:<nil> Atm:<nil> Qfq:<nil>}}
could not delete qdisc: functionality not yet implemented
```

I suspect this is because some qdisc stats fields are set by the command line tool when creating the qdisc, so this check fails:

https://github.com/florianl/go-tc/blob/master/qdisc.go#L157

Can you describe what should be done with the qdisc when these fields are set (and recommend some resources to read) so I could investigate making a PR? Can you suggest a way I can still delete the qdisc, or let me know if I'm approaching something the wrong way?

If I set the fields I linked to above to `nil`, I can remove the qdisc successfully, but there may be some danger in this I’m unaware of.

**Comment by florianl** [comment]
Hi!
Thanks for your feedback and example code. I really appreciate it! As you also identified the line of problem, I fixed it with https://github.com/florianl/go-tc/commit/6a5367f2e7ddbda07780cb09d897085b312ee5ec.
Hope this helped :)

**Comment by reprah** [comment]
Hi, I can confirm 6a5367f fixed the issue I reported. Thank you for the quick response and fix!
