### ISSUE TITLE
Can't delete BPF filters

### ISSUE THREAD

**Issue by sanfern** [florianl/go-tc#118]
### Describe the issue
BPF filter delete fails with error `netlink receive: no such file or directory `

### Expected behavior
Cleanup the filters created by the program.

### Minimal code example to reproduce the issue
Steps to reproduce the behavior.

<details><summary><code>go.mod</code></summary><br><pre>

module github.com/sanfern/go-tc-example

go 1.20

require (
        github.com/cilium/ebpf v0.10.0
        github.com/florianl/go-tc v0.4.2
        golang.org/x/sys v0.8.0
)

require (
        github.com/google/go-cmp v0.5.9 // indirect
        github.com/josharian/native v1.1.0 // indirect
        github.com/mdlayher/netlink v1.6.0 // indirect
        github.com/mdlayher/socket v0.1.1 // indirect
        golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd // indirect
        golang.org/x/sync v0.0.0-20210220032951-036812b2e83c // indirect
)
</br></pre></details>

<details><summary><code>main.go</code></summary><br><pre>
package main

import (
	"fmt"
	"github.com/cilium/ebpf"
	tc "github.com/florianl/go-tc"
	"github.com/florianl/go-tc/core"
	"golang.org/x/sys/unix"
	"net"
	"os"
	"time"
)

func main() {
	tcIface := "enp0s3"
	devID, err := net.InterfaceByName(tcIface)
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not get interface ID: %v\n", err)
		return
	}

	tcgo, err := tc.Open(&tc.Config{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not open rtnetlink socket: %v\n", err)
		return
	}

	// get all the qdiscs from all interfaces
	qdiscs, err := tcgo.Qdisc().Get()
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not get qdiscs: %v\n", err)
		return
	}
	clsactFound := false
	for _, qdisc := range qdiscs {
		iface, err := net.InterfaceByIndex(int(qdisc.Ifindex))
		if err != nil {
			fmt.Fprintf(os.Stderr, "could not get interface from id %d: %v", qdisc.Ifindex, err)
			return
		}
		if iface.Name == tcIface && qdisc.Kind == "clsact" {
			clsactFound = true
		}
	}

	if !clsactFound {
		qdisc := tc.Object{
			Msg: tc.Msg{
				Family:  unix.AF_UNSPEC,
				Ifindex: uint32(devID.Index),
				Handle:  core.BuildHandle(tc.HandleRoot, 0x0000),
				Parent:  tc.HandleIngress,
				Info:    0,
			},
			Attribute: tc.Attribute{
				Kind: "clsact",
			},
		}

		if err := tcgo.Qdisc().Add(&qdisc); err != nil {
			fmt.Printf("could not assign clsact to %s: %v, its already exists", tcIface, err)
		}
	}

	kernFile := "tc_program_kern.o"

	prg, err := ebpf.LoadCollection(kernFile)
	if err != nil {
		fmt.Println("LoadCollection error : ", err)
		return
	}
	defer prg.Close()

	bpfProg := prg.Programs["tc_program"]
	fd := uint32(bpfProg.FD())
	flags := uint32(0x1)

	filter := tc.Object{
		tc.Msg{
			Family:  unix.AF_UNSPEC,
			Ifindex: uint32(devID.Index),
			Handle:  0,
			Parent:  core.BuildHandle(tc.HandleRoot, tc.HandleMinIngress),
			Info:    0x300,
		},
		tc.Attribute{
			Kind: "bpf",
			BPF: &tc.Bpf{
				FD:    &fd,
				Flags: &flags,
			},
		},
	}
	if err := tcgo.Filter().Add(&filter); err != nil {
		fmt.Fprintf(os.Stderr, "could not attach filter for eBPF program: %v\n", err)
		return
	}

	fmt.Println("Attaching tc program is successful, resting ...")
	time.Sleep(2 * time.Second)

	if err := tcgo.Filter().Delete(&filter); err != nil {
		fmt.Fprintf(os.Stderr, "could not del filter for eBPF program: %v\n", err)
		return
	}
}
</br></pre></details>

### Environment
Provide some information about the system with the issue.
<pre>
$ uname -r
5.15.0-051500-generic
</pre>

[Ref code](https://github.com/sanfern/go-tc-example)

**Comment by florianl** [comment]
`no such file or directory` is an error message from the Kernel and hints towards wrong user input/API usage.

Therefore repeating my question from https://github.com/florianl/go-tc/issues/17#issuecomment-1561773424:

Did you try to list attached filters with something alone the following lines?
```
tcgo.Filter().Get(&tc.Msg{
		Family:  unix.AF_UNSPEC,
		Ifindex: uint32(devID.Index),
		Handle:  0x0,
		Parent:  core.BuildHandle(tc.HandleRoot, tc.HandleMinIngress),
	})
```
If you compare the reported filters with your initial given input, you will notice differences. In particular pay attention to `tc.Msg.Info`.
As a consequence, if you take the reported filter and use the reported object as input to the `Delete()` function, you should be able to delete filter.

**Comment by sanfern** [comment]
Thanks @florianl,  I tested with above recommended approach. This works with one filter attached to the interface. If we have multiple filters for a given interface. How do we delete the particular filter. I have updated the code in my repo with the fix. 
```
tcfilts, err := tcgo.Filter().Get(&tc.Msg{
		Family:  unix.AF_UNSPEC,
		Ifindex: uint32(devID.Index),
		Handle:  0x0,
		Parent:  core.BuildHandle(tc.HandleRoot, tc.HandleMinIngress),
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "could not get filters for eBPF program: %v\n", err)
		return
	}
	for i := range tcfilts {
		fmt.Println(tcfilts[i].Msg.Info)
	}

	filter1 := tc.Object{
		tc.Msg{
			Family:  unix.AF_UNSPEC,
			Ifindex: uint32(devID.Index),
			Handle:  0,
			Parent:  core.BuildHandle(tc.HandleRoot, tc.HandleMinIngress),
			Info:    tcfilts[0].Msg.Info,
		},
		tc.Attribute{
			Kind: "bpf",
			BPF: &tc.Bpf{
				FD:    &fd,
				Flags: &flags,
			},
		},
	}
```

**Comment by florianl** [comment]
> How do we delete the particular filter. 

The combination of `Handle`, `Parent` and `Info` uniquely identify each filter. So you should be able to differentiate them using a combination of these arguments.

**Comment by sanfern** [comment]
Ah nice. Thanks @florianl . This really helped.
