### ISSUE TITLE
Guidance for creating filters with go-tc

### ISSUE THREAD

**Issue by reprah** [florianl/go-tc#12]
Hi, I’m using go-tc to rate limit ingress traffic for an interface [using an IFB](https://wiki.gentoo.org/wiki/Traffic_shaping#Theory).

Part of this process is creating a filter on an ingress qdisc that mirrors ingress traffic to the IFB. This command seems to create 3 filters (3 are also seen using `Filter.Get()`).

```
root@box:~# tc filter add dev wg0 parent ffff: protocol all prio 10 u32 match u32 0 0 flowid 1:1 action mirred egress redirect dev ifbwg0
root@box:~# tc -d filter show dev wg0 ingress
filter protocol all pref 10 u32 chain 0
filter protocol all pref 10 u32 chain 0 fh 800: ht divisor 1
filter protocol all pref 10 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 flowid 1:1 not_in_hw
  match 00000000/00000000 at 0
        action order 1: mirred (Egress Redirect to device ifbwg0) stolen
        index 1 ref 1 bind 1
```
This is my code equivalent for the 2nd filter, as an example:

```
package main

import(
	"fmt"
	"net"
	"os"
	"golang.org/x/sys/unix"
	"github.com/florianl/go-tc"
	"encoding/json"
)

func main() {
	rtnl, err := tc.Open(&tc.Config{})
	if err != nil {
	    fmt.Fprintf(os.Stderr, "could not open rtnetlink socket: %v\n", err)
	    return
	}
	defer func() {
	    if err := rtnl.Close(); err != nil {
	        fmt.Fprintf(os.Stderr, "could not close rtnetlink socket: %v\n", err)
	    }
	}()

	devID, err := net.InterfaceByName("wg0")
	if err != nil {
	    fmt.Fprintf(os.Stderr, "could not get interface ID: %v\n", err)
	    return
	}

	qdiscs, err := rtnl.Qdisc().Get()

	if err != nil {
	    fmt.Fprintf(os.Stderr, "could not get qdiscs: %v\n", err)
	    return
	}

	var ingressQdisc tc.Object

	for _, qdisc := range qdiscs {
	    iface, err := net.InterfaceByIndex(int(qdisc.Ifindex))
	    if err != nil {
	        fmt.Fprintf(os.Stderr, "could not get interface from id %d: %v", qdisc.Ifindex, err)
	        return
	    }
		if iface.Name == "wg0" && qdisc.Attribute.Kind == "ingress" {
			ingressQdisc = qdisc
		}
	}


	// add filter to ingress qdisc of wg0
	newFilter := tc.Object{
		tc.Msg{
			Family:  unix.AF_UNSPEC,
			Ifindex: uint32(devID.Index),
			Parent: ingressQdisc.Msg.Handle,
		},
		tc.Attribute{
			Kind: "u32",
			Chain: 0,
			U32: &tc.U32{
				Divisor: 1,
			},
		},
	}

	s, _ := json.MarshalIndent(newFilter, "", "\t")
	fmt.Printf("adding filter: %s\n", string(s))

	if err := rtnl.Filter().Replace(&newFilter); err != nil {
		fmt.Printf("couldn't add filter to wg0: %v\n", err)
		return
	}

}
```

Running the program shows:
```
couldn't add filter to wg0: netlink receive: invalid argument
```

I can’t seem to create any of the filters shown above (after deleting the existing ones) and the errors provide very little information so I don't know what to correct.

Do you have guidance on how I can debug why the filters I'm creating are invalid (like how to get better errors from netlink) or suggestions about what I can read that will help me understand how a filter should be created?

I have tried:

- creating the filters on the command line and then printing out the `Filter` structs using `Filter.Get()` to check that I’m setting required fields. I’m not sure if all the values I chose are correct
- looking at the [tests for filters](https://github.com/florianl/go-tc/blob/master/filter_test.go) to see if I could create a simple filter and then build incrementally from that
- looking at the referenced C code (for example [pkt_sched.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/pkt_sched.h)) to see what values I might be missing, or what some flag means.

Thanks!

**Comment by florianl** [comment]
Hi :)
the feedback from netlink is very limited as you already have noticed. ` invalid argument` is usually all the kernel returns if an argument is wrong or missing.
This library only provides direct access to the underlying kernel structures to create filters, qdiscs and others. There is no argument validation in place like the original tc from iproute2 does.

When facing such an issue, I usually find myself comparing the strace output from my code with the output from the original tc tool.

Florian

**Comment by reprah** [comment]
Thanks, I will try that. If I find anything useful I can submit a PR adding more documentation or tests too, if that is welcome.
