### ISSUE TITLE
Version tag no longer available

### ISSUE THREAD

**Issue by RixhersAjazi** [florianl/go-tc#13]
Hi there,

Firstly, thank you for making this library available to the public. I wanted to know if it is expected that there be no more version tags on github for this project? A project I am working on was using  v0.1.1 (5c65c840f086) but our builds started to fail recently with: 
```
 [  261s] + /usr/bin/go get -d
 [  318s] go: github.com/florianl/go-tc@v0.1.1-0.20200617173005-5c65c840f086: invalid pseudo-version: preceding tag (v0.1.0) not found
```

For now should we just pull from master all the time?

**Comment by florianl** [comment]
Hi :)

Great to hear this package help you :+1: 

Yes - the git tag was deleted. I realized that tagging a git version on this project is not the best way to go. E.g. the git tag was not updated when new features where added, buges fixed or changes were made to the API.
Nonetheless you still can tag a version for your project using modules:
```
$ go get github.com/florianl/go-tc@master
$ go get github.com/florianl/go-tc@5c65c840f0867a45a01f9de9de0db271f603ec1f
```

As this is a private project and I try to keep the management overhead at a minimum, I will also not use git tags in the future. 

I'm sorry for the caused problems.

Florian

**Comment by RixhersAjazi** [comment]
Hi there, not a problem! Was just making sure that was expected or not and if we should just expect to use master. Also right, my team is unblocked as I just tagged master @ that exact hash. 

Thanks again, have a good weekend.
