### ISSUE TITLE
general struct alignment

### ISSUE THREAD

**Issue by twaapo** [florianl/go-tc#16]
Hi,

How could one test and know how the kernel uses tc structs? Perhaps this is architecture dependent. I think the current code still has some pitfalls where debugging can be somewhat time consuming. I just run into the ones I am using.

eg.
```go
// ConnmarkParam from include/uapi/linux/tc_act/tc_connmark.h
type ConnmarkParam struct {
    Index   uint32
    Capab   uint32
    Action  uint32
    RefCnt  uint32
    BindCnt uint32
    Zone    uint16
    _       [2]byte //pad ???
}
```
I believe the above struct is indeed 24bytes on "wire" rather than 22. One clue could be 22%4 = 2. Perhaps padding the struct definitions would be the way to go with this? Simple marshalStruct() would then work as expected.

Edit:
On second thought I think 22%4 = 2 thing is garbage, and struct alignment is based on normal C conventions. Whether the padding is on wire is based on if the struct is serialized or memcpy'd by the kernel.

**Comment by florianl** [comment]
Hi!
And thanks for reporting the issue!
If possible, can you provide a recipe for reproducing the error.
Maybe a runnable program is good and/or a tc cmd that demonstrates your reporting.

Flo

**Comment by florianl** [comment]
Issue has been fixed with https://github.com/florianl/go-tc/commit/3e95a8d8a944478c7254962d291df91858ecd499.
