### ISSUE TITLE
Cannot set protocol and pref fields in flower filter

### ISSUE THREAD

**Issue by dennisafa** [florianl/go-tc#21]
Hello, I'm adding a tc flower filter using the following code:
```
flower := tc.Flower{
		Actions:         &actions,
		KeyEthType:      ethType,
		KeyVlanID:       params.vlanEndpoint,
		KeyVlanEthType:  ethType,
		KeyCVlanID:      params.vlanLink,
		KeyCVlanEthType: ethType,
	}
	attrFlower := tc.Attribute{Kind: "flower", Flower: &flower}
	objFlower := tc.Object{Msg: params.msg, Attribute: attrFlower}

	if err := params.rtnl.Filter().Add(&objFlower); err != nil {
		fmt.Fprintf(os.Stderr, "could not add filter flower: %v\n", err)
	} else {
		fmt.Fprintf(os.Stderr, "added filter flower\n")
	}
```
The following is what I get from a `tc -s` command:

```
filter protocol all pref 49152 flower chain 0
filter protocol all pref 49152 flower chain 0 handle 0x1
  enc_key_id 2
  enc_dst_port 4789
  not_in_hw
	action order 1: vlan  push id 1 protocol 802.1Q priority 0 pipe
	 index 1 ref 1 bind 1 installed 3 sec used 3 sec
	Action statistics:
	Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
	backlog 0b 0p requeues 0

	action order 2: vlan  push id 1 protocol 802.1Q priority 0 pipe
	 index 2 ref 1 bind 1 installed 3 sec used 3 sec
	Action statistics:
	Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
	backlog 0b 0p requeues 0

	action order 3: mirred (Egress Mirror to device  eth0) stolen
	index 3 ref 1 bind 1 installed 3 sec used 3 sec
	Action statistics:
	Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
	backlog 0b 0p requeues 0
```
In this particular line: `filter protocol all pref 49152 flower chain 0` I would like to be able to set the `pref` and the `protocol`, but I do not see the fields in f_flower.go that would allow me to do this. Any help would be appreciated!

**Comment by florianl** [comment]
Hi @dennisafa 
The preference and protocol information applied to a filter are encoded in the `Info` field of `Msg` https://pkg.go.dev/github.com/florianl/go-tc#Msg. The upper 16 bits hold the priority information while the lower 16 bits hold protocol information. So it's part of a `filter` in general and not the filter kind specification.

**Comment by dennisafa** [comment]
> Hi @dennisafa
> The preference and protocol information applied to a filter are encoded in the `Info` field of `Msg` https://pkg.go.dev/github.com/florianl/go-tc#Msg. The upper 16 bits hold the priority information while the lower 16 bits hold protocol information. So it's part of a `filter` in general and not the filter kind specification.

Awesome, thanks so much!

**Comment by SMALL-head** [comment]
> Hi @dennisafa The preference and protocol information applied to a filter are encoded in the `Info` field of `Msg` https://pkg.go.dev/github.com/florianl/go-tc#Msg. The upper 16 bits hold the priority information while the lower 16 bits hold protocol information. So it's part of a `filter` in general and not the filter kind specification.

Thanks for your answer!. That's a little bit confusing, because the name 'Info' has nothing to do with prio and protocol! I wonder that is there any reference that can help me understand it? For example, how the attribute 'Info' maps to the filter config in Linux source code? The Info attribute may stand for another configuration when adding qdisc or class, so how do I know what 'Info' stands for in different situation.

**Comment by florianl** [comment]
@SMALL-head this packages provides a low-level Go native interface to the [netlink](http://man7.org/linux/man-pages/man7/netlink.7.html) based [traffic control system](http://man7.org/linux/man-pages/man8/tc.8.html) of [rtnetlink](http://man7.org/linux/man-pages/man7/rtnetlink.7.html). As such it follows the naming and conventions of the Linux kernel internals.

In some parts, these namings and conventions overlap with the well known user space tooling [tc](https://man7.org/linux/man-pages/man8/tc.8.html). But for some parts the user space tool [tc](https://man7.org/linux/man-pages/man8/tc.8.html)  provides a more high level abstraction. This package does not provide this kind of abstraction as it is not intended to be a Go copy of user space tool, whereas this package can be the base for another package that provides these abstractions.

Speaking so, https://pkg.go.dev/github.com/florianl/go-tc#Msg can be mapped to its Linux kernel equivalent [tcmsg](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/rtnetlink.h?h=v6.10#n605).
