### ISSUE TITLE
Setting the priority of a rule

### ISSUE THREAD

**Issue by dennisafa** [florianl/go-tc#25]
Hello! I'm wondering how to add a priority to a given rule. For example:
```
tc filter add eth0 ingress flower \
  prio 1000 \
  action tunnel_key unset \
```
I don't see where this field would be added. Any help would be appreciated!

**Comment by florianl** [comment]
I'm not aware of `prio` attribute (other than `vlan prio`) in the flower filter. See also https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/tc/f_flower.c#n49

So the only `prio` attribute that i'm aware of is from the filter attributes themself (see https://github.com/florianl/go-tc/issues/21#issuecomment-771089889). And in the filter attributes it is encoded in the `Info` field of the struct.
For the `tc` counterpart see  https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/tc/tc_filter.c#n186

**Comment by dennisafa** [comment]
> I'm not aware of `prio` attribute (other than `vlan prio`) in the flower filter. See also https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/tc/f_flower.c#n49
> 
> So the only `prio` attribute that i'm aware of is from the filter attributes themself (see [#21 (comment)](https://github.com/florianl/go-tc/issues/21#issuecomment-771089889)). And in the filter attributes it is encoded in the `Info` field of the struct.
> For the `tc` counterpart see https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/tc/tc_filter.c#n186

Thank you - I just constructed a different Msg object with a different pref field and that seems to have given me the results I was looking for.
