### ISSUE TITLE
Cgroup filter support

### ISSUE THREAD

**Issue by superfashi** [florianl/go-tc#26]
[tc-cgroup(8)](https://man7.org/linux/man-pages/man8/tc-cgroup.8.html) is a control group based traffic control filter. Supporting it shouldn't be very hard judging by the amount of options this filter takes.

**Comment by florianl** [comment]
The `match` argument to [tc-cgroup(8)](https://man7.org/linux/man-pages/man8/tc-cgroup.8.html) requires the implementation of [tc-ematch(8)](https://man7.org/linux/man-pages/man8/tc-ematch.8.html). 
I'm happy to discuss implementations for [tc-ematch(8).](https://man7.org/linux/man-pages/man8/tc-ematch.8.html) and accept PRs.

**Comment by superfashi** [comment]
It's not really required, just an option that you don't have to implement for now. In fact `basic` and `flow` filters take `ematch` as well.

**Comment by florianl** [comment]
With https://github.com/florianl/go-tc/commit/160168a572005491daded87b725282dd1455ecad I've added the `cgroup` filter without `ematch` support.

Therefore closing this issue.
