### ISSUE TITLE
Cannot list SFQ qdisc

### ISSUE THREAD

**Issue by skystar-p** [florianl/go-tc#29]
For any of the interface have SFQ qdisc, go-tc failed to fetch it with the error message below:
```
panic: extractTCAOptions(): unsupported kind: sfq
```

How can I correctly list SFQ qdisc? Thank you.

**Comment by florianl** [comment]
hi @skystar-p 
As the error message indicates, `sfq` is not implemented.

**Comment by florianl** [comment]
`sfq` got implemented with https://github.com/florianl/go-tc/commit/3a632c0daf8203c00937a8c928ce3d46008cb072. Therefore closing this issue.
