### ISSUE TITLE
Error getting egress filter

### ISSUE THREAD

**Issue by lePereT** [florianl/go-tc#3]
Hi Florian

I'm attempting to use go-tc to programmatically apply filtering and shaping banks. My main method for doing this is to use `tc` to implement the rules and then the relevant go-tc `.Get()` functions to examine the actual tc.objects created (so that I can recreate these objects with go-tc)

At the moment I'm using the following `tc` commands to divert ingress traffic to an IFB:
```
tc qdisc add dev eth0.32 handle ffff: ingress
tc filter add dev eth0.32 parent ffff: protocol ip u32 match u32 0 0 action mirred egress redirect dev ifb0
```

When I use `tc filter show dev eth0.32 ingress` to check the status of the filters created by tc I get the following info:

```
filter parent ffff: protocol ip pref 49152 u32 chain 0
filter parent ffff: protocol ip pref 49152 u32 chain 0 fh 800: ht divisor 1
filter parent ffff: protocol ip pref 49152 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 terminal flowid ??? not_in_hw
  match 00000000/00000000 at 0
	action order 1: mirred (Egress Redirect to device ifb0) stolen
 	index 1 ref 1 bind 1
```

All good. I then use the following code in go-tc to try and examine these tc objects:

```
	filters, err := rtnl.Filter().Get(&tc.Msg{Family: unix.AF_UNSPEC, Ifindex: uint32(iface.Index), Parent: tc.BuildHandle(0xffff, 0)})
	spew.Dump(filters)
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not get filter: %v\n", err)
		return err
	}
```
I can get at two of the filters but the third one errors out, giving me the following message:
 ```
could not get filter: unmarshalU32()	7
	[136 0 1 0 11 0 1 0 109 105 114 114 101 100 0 0 48 0 4 0 20 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 24 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 72 0 2 0 32 0 2 0 1 0 0 0 0 0 0 0 4 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 2 0 0 0 36 0 1 0 121 184 5 0 0 0 0 0 121 184 5 0 0 0 0 0 0 0 0 0 0 0 0 0 215 182 7 0 1 0 0 0]
```
At this point I'm stuck!

**Comment by florianl** [comment]
thanks for the detailed report! I will have a look at it and report back.

**Comment by florianl** [comment]
The message of the error might be missleading. Attribute 7 corresponds to `tcaU32Act` [1], which is not implemented in `unmarshalU32` [2]. 

I will start working on this.

[1] https://github.com/florianl/go-tc/blob/master/f_u32.go#L19
[2] https://github.com/florianl/go-tc/blob/master/f_u32.go#L82

**Comment by florianl** [comment]
i've created a first PR to implement `tcaU32Act`. it is not finished yet.

**Comment by lePereT** [comment]
Thanks man! It's been really interesting using your library, I'm learning a lot more about tc and netlink. 

One other point I wanted to raise with you (which may be worth its own issue, or not) is around the ergonomics of clearing qdiscs, filters or classes from an interface. Using `tc` you can simply do a `tc qdisc delete dev eth0 root`. However, in go-tc you have to provide a tc object that can be properly validated by the code logic. Of course this requires one to specify a qdisc type, etc. Is there any scope for changing the logic for the deletion functions?

**Comment by florianl** [comment]
i've just updated https://github.com/florianl/go-tc/pull/4. it is now possible, to read and set actions for filters.

regarding your other point:
the idea for this package so far is, to directly translate the kernel interface into Go structures. So, many tricks and tweaks, which are done by the original `tc` are not implemented. but it sounds like an interesting idea, to build a command line tool on top of this package, which covers this.

**Comment by lePereT** [comment]
> ... So, many tricks and tweaks, which are done by the original tc are not implemented...

I totally understand the scope of this package, and tbh I'm learning a hella lot from this low level manipulation. And my code is fast too :)

Thanks again bossman
