### ISSUE TITLE
pfifo_fast support

### ISSUE THREAD

**Issue by superfashi** [florianl/go-tc#30]
From [documentation](https://man7.org/linux/man-pages/man8/tc-pfifo_fast.8.html), `pfifo_fast` seems to be the default qdisc of each interface. Looks like a relatively easy qdisc to implement by the look of the doc, please consider adding support for it.

**Comment by florianl** [comment]
Hi,
And thanks for your interest and request!
Reading [pfifo_fast(8)](https://man7.org/linux/man-pages/man8/tc-pfifo_fast.8.html) it sounds to me like a description of an in-Kernel behaviour. Can you name a user space tool that can set or edit `pfifo_fast`? And if so, can you provide a full argument list needed for it?

**Comment by superfashi** [comment]
Not quite sure how to set it. I'm using CentOS 7 and when I run `tc qdisc`, I see some network interfaces are using qfifo_fast.

Here's an interception of `strace` on `tc qdisc`, don't know if that will be helpful.

```
{{len=176, type=RTM_NEWQDISC, flags=NLM_F_MULTI, seq=1627447511, pid=2653462}, {tcm_family=AF_UNSPEC, tcm_ifindex=if_nametoindex("eth0"), tcm_handle=0, tcm_parent=4294967295, tcm_info=2}, [{{nla_len=15, nla_type=TCA_KIND}, "pfifo_fast"}, {{nla_len=24, nla_type=TCA_OPTIONS}, "\x03\x00\x00\x00\x01\x02\x02\x02\x01\x02\x00\x00\x01\x01\x01\x01\x01\x01\x01\x01"}, {{nla_len=5, nla_type=TCA_HW_OFFLOAD}, 0}, {{nla_len=48, nla_type=TCA_STATS2}, [{{nla_len=20, nla_type=TCA_STATS_BASIC}, {bytes=748738, packets=5330}}, {{nla_len=24, nla_type=TCA_STATS_QUEUE}, {qlen=0, backlog=0, drops=0, requeues=0, overlimits=0}}]}, {{nla_len=44, nla_type=TCA_STATS}, {bytes=748738, packets=5330, drops=0, overlimits=0, bps=0, pps=0, qlen=0, backlog=0}}]}
```

**Comment by florianl** [comment]
Thanks for your feedback and the strace output! :+1: 
With commit https://github.com/florianl/go-tc/commit/d134361689b4ba4389160e486d79968fd9b36a0f I have added the qdisc `prio` which also can decode `pfifo_fast`.

**Comment by superfashi** [comment]
Thanks!
