### ISSUE TITLE
Missing skbedit action

### ISSUE THREAD

**Issue by kamilpoleszczuk** [florianl/go-tc#35]
Hi!
Currently go-tc does not support skbedit action:

https://github.com/florianl/go-tc/blob/master/m_action.go#L41
https://man7.org/linux/man-pages/man8/tc-skbedit.8.html

are there any plans for adding it? If so, what's the probable timeline?

**Comment by florianl** [comment]
Hi @kamilpoleszczuk 

Thank you for your interest in this project. There is no timeline for adding it.

**Comment by florianl** [comment]
skbedit was added with https://github.com/florianl/go-tc/commit/c95922272f80c6856b01c3264b7ef4b305197aca. Therefore closing this issue.
