### ISSUE TITLE
works on centos8, doesn't work on centos7

### ISSUE THREAD

**Issue by neoareslinux** [florianl/go-tc#38]
**Describe the issue**
as title, it seems that go-tc works on centos8, doesn't work on centos7.
does go-tc has supported kernel version lists doc?  i can't not find in repo.

**Expected behavior**
i  would expect the tc-lib will recognize the different kernel verion to be compatible with them

**Minimal code example to reproduce the issue**
on centos 7, build the example and run will get the error report
could not get qdiscs: extractTCAOptions(): unsupported kind pfifo_fast: unknown kind

**Comment by florianl** [comment]
Hi!
Not every qdisc/class or filter is available for every kernel. Can you name the kernel version that is used in CentOS 7? And did you check if this kernel version supports `pfifo_fast`?

**Comment by neoareslinux** [comment]
i have tested go-tc on centos7 witch commit  d134361, it  works well. thanks
