### ISSUE TITLE
Feature request: CAKE qdisc

### ISSUE THREAD

**Issue by lePereT** [florianl/go-tc#8]
CAKE landed in linux 4.19. It's probably the easiest AQM to use with a WAN connection. Do you have any plans to add it? 😃

**Comment by florianl** [comment]
There is no plan yet to add it. Pull requests are welcome :)

**Comment by florianl** [comment]
`cake` has been added in https://github.com/florianl/go-tc/commit/69b0c913257724fbbbf4717192143a434c14e88e. Therefore closing this issue.
