### ISSUE TITLE
How about rtnl.SetOption(netlink.ExtendedAcknowledge, true) by default?

### ISSUE THREAD

**Issue by Asphaltt** [florianl/go-tc#99]
Recently, I use `go-tc` to set tc rules. But I didn't know to `rtnl.SetOption(netlink.ExtendedAcknowledge, true)`.  As a result, I got error message `netlink receive: invalid argument`. After I set the option, `netlink receive: invalid argument, offset: 0, message: "Filter kind and protocol must be specified"`.

As the [Introduction to Netlink — The Linux Kernel documentation](https://kernel.org/doc/html/next/userspace-api/netlink/intro.html#extended-ack) doc recommends, **Extended ACKs greatly improve the usability of Netlink and should always be enabled, appropriately parsed and reported to the user**.

How about `rtnl.SetOption(netlink.ExtendedAcknowledge, true)` by default?

Since 4.12 kernel, [netlink: extended ACK reporting](https://github.com/torvalds/linux/commit/2d4bc93368f5a0ddb57c8c885cdad9c9b7a10ed5).

In `go-tc`, it's OK to try `rtnl.SetOption(netlink.ExtendedAcknowledge, true)`, and ignore error `ENOPROTOOPT` if it fails.

**Comment by florianl** [comment]
With [`func (*Tc) SetOption(..)`](https://pkg.go.dev/github.com/florianl/go-tc#Tc.SetOption) there is already a way to set additional attributes, like `NETLINK_EXT_ACK`, on the netlink connection.
Setting `NETLINK_EXT_ACK` by default might help some users but introduces code complexity and might cause issues in some environments and cause confusion by users of this package.
Therefore with [`func (*Tc) SetOption(..)`](https://pkg.go.dev/github.com/florianl/go-tc#Tc.SetOption) users do have the option to set `NETLINK_EXT_ACK` and are encouraged to do so.
Going forward I think it is best to improve documentation and make users of this package more are of [`func (*Tc) SetOption(..)`](https://pkg.go.dev/github.com/florianl/go-tc#Tc.SetOption).

**Comment by Asphaltt** [comment]
Yes, I agree with you.

How about add the following code snippet to the example code snippet of **README.md**?

```Go
	// Extended ACK is recommended to always be enabled.
	// It is supported since 4.12 kernel.
	//
	// If it is not supported, the errno `ENOPROTOOPT` will be reported, and can
	// be ignored.

	err = rtnl.SetOption(netlink.ExtendedAcknowledge, true)
	if err != nil && !errors.Is(err, unix.ENOPROTOOPT) {
		_ = rtnl.Close()
		return nil, err
	}
```

It's in order to make users aware of it.

**Comment by florianl** [comment]
yes - that looks like a good plan :+1:

**Comment by florianl** [comment]
Adding it to the README in https://github.com/florianl/go-tc/pull/100 is a good start I think.
